language: java
env:
  - CODACY_PROJECT_TOKEN=3b087146f18048b8b9d3ce8ade8a0610
jdk:
  - oraclejdk8
script: mvn clean install
before_install:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly

after_success:
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
